language: node_js
branches:
  only:
    - master
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
before_script:
  - 'npm install -g grunt-cli coveralls'
script:
  - 'grunt test:parts && cat generated/lcov.info | coveralls'
